services:
  socks-service:
    build: .
    image: socks-service-image
    container_name: socks-service-container
    ports:
      - "8080:8080"
    depends_on:
      - socks-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://socks-db:5432/socks-db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  socks-db:
    image: postgres:16.1
    container_name: socks-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=socks-db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
